// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfsMtPBiEe_PbKiV_KsLaDW7dG2X0ALJ4',
    appId: '1:337756546448:web:ef97f56591f3a1c7d57f15',
    messagingSenderId: '337756546448',
    projectId: 'be-real-dating',
    authDomain: 'be-real-dating.firebaseapp.com',
    databaseURL: 'https://be-real-dating-default-rtdb.firebaseio.com',
    storageBucket: 'be-real-dating.appspot.com',
    measurementId: 'G-CFY8WX6JFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Z9rHX3US0BAcwBgFzEhTlhE58-ZebVs',
    appId: '1:337756546448:android:f5a1f8493a04c230d57f15',
    messagingSenderId: '337756546448',
    projectId: 'be-real-dating',
    databaseURL: 'https://be-real-dating-default-rtdb.firebaseio.com',
    storageBucket: 'be-real-dating.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfHcHYCGOuwtortqw3asOch8fDGVKsgBk',
    appId: '1:337756546448:ios:02c657b3c79e32dbd57f15',
    messagingSenderId: '337756546448',
    projectId: 'be-real-dating',
    databaseURL: 'https://be-real-dating-default-rtdb.firebaseio.com',
    storageBucket: 'be-real-dating.appspot.com',
    iosBundleId: 'com.example.aiDating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfHcHYCGOuwtortqw3asOch8fDGVKsgBk',
    appId: '1:337756546448:ios:02c657b3c79e32dbd57f15',
    messagingSenderId: '337756546448',
    projectId: 'be-real-dating',
    databaseURL: 'https://be-real-dating-default-rtdb.firebaseio.com',
    storageBucket: 'be-real-dating.appspot.com',
    iosBundleId: 'com.example.aiDating',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfsMtPBiEe_PbKiV_KsLaDW7dG2X0ALJ4',
    appId: '1:337756546448:web:d0df2657e37c50ead57f15',
    messagingSenderId: '337756546448',
    projectId: 'be-real-dating',
    authDomain: 'be-real-dating.firebaseapp.com',
    databaseURL: 'https://be-real-dating-default-rtdb.firebaseio.com',
    storageBucket: 'be-real-dating.appspot.com',
    measurementId: 'G-NLVQ93YSTJ',
  );
}
